server:
  port: 9412
spring:
  application:
    name: sleuth-pro9412
  zipkin: #追踪
    base-url: http://localhost:9411/  #追踪路径  就是
  sleuth:
    sampler: #抓取
      probability: 1 #可行性 最大值1  设置为1 表示所有路径都抓取到
eureka:
  instance:
    hostname: sleuth-pro9412
    prefer-ip-address: true #开启前缀
    instance-id: sleuth #实例名称
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/