server:
  port: 8088
spring:
  application:
    name: cloudfeignhystrix8088
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
feign:
  hystrix:
    enabled: true