server:
  port: 9527

spring:
  application:
    name: cloud_gateway_9527
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
#          uri: http://localhost:8087 #匹配后提供服务的路由地址 没有进行负载均衡
          uri: lb://CLOUD-PROVIDER-SERVICE
          predicates:
            - Path=//getRibbon/** #断言，路径相匹配的进行路由
#            - After=2020-07-29T11:18:14.038+08:00[Asia/Shanghai]
#            - Cookie=username,mq

eureka:
  instance:
    hostname: cloud_gateway
  client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://eureka7002.com:7002/eureka/



