server:
  port: 9012
spring:
  application:
    name: nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #  暴露web地址
management:
  endpoint:
    web:
      exposure:
        include: "*"