server:
  port: 3366

eureka:
  instance:
    hostname: cloud_config3366
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka/ #注册的具体路径

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: cloud_config3366